#!/bin/bash
cp -p ./libraries/commonlibs.mq4 "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Libraries/" 
cp -p ./include/commonlibs.mqh "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Include/" 
cp -p ./include/defvarsExtrn.mqh "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Include/"
cp -p ./include/defvars.mqh "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Include/"
cp -p ./include/signal.mqh "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Include/"
cp -p ./useFunction.mqh "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Experts/"
cp -p ./scalper.mq4 "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Experts/"
cp -p ./indicators/ticks.mq4 "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Indicators/" 
cp -p ./Scripts/OpenOrder.mq4 "/home/valera_k2000/.wine/drive_c/Program Files (x86)/MetaTrader 4 - RoboForex/MQL4/Scripts/" 
