	ON SHUTDOWN

	IF TYPE("m.goApp") = 'O'
		m.goApp.Release()
		RELEASE m.goApp
		goApp = .NULL.
	ENDIF

*!*		ON ERROR err = .t.
*!*		CLEAR ALL
	SET STATUS BAR ON
	SET MESSAGE TO
	SET BELL ON
	POP KEY ALL
	RESTORE MACROS
	SET CLASSLIB TO
	SET SYSMENU TO DEFAULT
	ON ERROR
	CLEAR EVENTS
