#DEFINE CRLF CHR(13)+CHR(10)
#DEFINE APP_WRONG_SUPERCLASS_LOC ""
#DEFINE APP_CANNOT_RUN_LOC ""
#DEFINE APP_OBJ_NAME SUO_APP
#DEFINE APP_OBJ_NAME_QUOTED "SUO_APP"
#DEFINE APP_NAME_QUOTED "Консервный цех"